# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Tour
  #   url: tour
  #   weight: 10
  - name: About
    weight: 1
  - name: Mission
    url: mission
    parent: About
  - name: Research
    url: research
    parent: About
  - name: Training
    url: training
    parent: About
  - name: Fellowships
    url: 'fellowship'
    weight: 2
  - name: People
    url: people
    weight: 3
  - name: Events
    url: event
    weight: 4
  - name: News
    url: news
    weight: 5
  - name: Contact
    url: '#contact'
    weight: 6

  # - name: Outreach
  #   url: outreach
  #   weight: 80
  # - name: Research
  #   url: research
  #   weight: 40
  # - name: Publications
  #   url: publication
  #   weight: 50
